### ISSUE TITLE
Error when launched

### ISSUE THREAD

**Issue by Snoopy1205** [churrufli/forgelauncher#5]
I went back from a SNAPSHOT to a Release and ever since, I get an error every time I use the launcher; forge itself still launches and works perfect.
The error is:
"Unhandled exception has occurred in your application..."
Details:
"************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Forge_Launcher.fn.CheckforForgeUpdates(Object AskforReinstall, Object NewInstall)
   at Forge_Launcher.fl.Timer1_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

**Comment by maforget** [comment]
Your problem is when doing CheckRelease(), you are doing a couple of date manipulation, but on the assumption that the date format is always the same. I believe you have a date format of 25/11/2021, but if I use 25-Nov-2021 it crashes. Also you have a 2020 year hard coded that isn't useful now in 2021. 

Here is a simpler way to fix it. This just reads the maven-metadata.xml and takes the last line. You will need to add System.Xml reference to your project.

Your whole Function can be changed: https://github.com/churrufli/forgelauncher/blob/04655a1d554edd0cde18c4722f7d497ed532c03e/Forge%20Launcher/fn.vb#L353-L454 

```
  Public Shared Function CheckRelease()
      Dim metadata = vars.url_release + "maven-metadata.xml"
      Dim xml = fn.ReadWeb(metadata)
      Dim doc As New System.Xml.XmlDocument()
      doc.LoadXml(xml)
      Dim nodes As System.Xml.XmlNodeList = doc.DocumentElement.SelectNodes("//version")
      Dim lastVersion = nodes.Item(nodes.Count - 1).InnerText
      Dim finalURL = String.Format("{0}{1}/forge-gui-desktop-{1}.tar.bz2", vars.url_release, lastVersion)
      CheckRelease = finalURL
  End Function
```

But even then after asking if you want to install the version, you go and completely ignore the release version and install the snapshot either way. This is the culprit: https://github.com/churrufli/forgelauncher/blob/04655a1d554edd0cde18c4722f7d497ed532c03e/Forge%20Launcher/fn.vb#L552 

It can be fixed with 

`Dim link = If(typeofupdate = "snapshot", Split(GetCheckAutomatic(), "#")(1), vs)`

Some pointer I can give you after checking your code:
- For HTML you could use the HTMLAgilityPack to parse HTML more easily.
- For reading and writing your version.txt, I would either use serialization and deserialization. It a lot easier to access your setting by assigning them to objects (ex: log.forge_version). You can even easily create the classes needed with Visual Studio by copying your version.txt and using Edit->Paste Special -> Paste XML as classes.
- Use Nuget packages when possible, I couldn't build your code because I didn't have ICSharpCode.SharpZipLib.dll at your hardcoded path.

**Comment by churrufli** [comment]
thanks @Nigol for your fix, much better to take the latest version of maven-metadata.xml than what I did before 😅 I really appreciate the help!
